In [ ]:
#Exercise 1
# Function to check if the number is prime
def is_prime(number):
    if number <= 1:
        return False
    for i in range(2, int(number ** 0.5) + 1):  # Check divisibility up to the square root of the number
        if number % i == 0:
            return False
    return True

# Ask user for input
user_input = int(input("Enter a number: "))

# Check if the number is prime and print the result
if is_prime(user_input):
    print(f"{user_input} is a prime number.")
else:
    print(f"{user_input} is not a prime number.")

11 is a prime number.


In [ ]:
#Exercise 2
# Fibonacci sequence generator in Python
def fibonacci_sequence(n):
    sequence = []
    a, b = 0, 1
    for _ in range(n):
        sequence.append(a)
        a, b = b, a + b
    return sequence

# Ask user for input
try:
    num_terms = int(input("Enter the number of Fibonacci numbers to display: "))
    if num_terms <= 0:
        print("Please enter a positive integer.")
    else:
        result = fibonacci_sequence(num_terms)
        print("Fibonacci sequence:", result)
except ValueError:
    print("Invalid input. Please enter a valid number.")


Fibonacci sequence: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]


In [ ]:
#Exercise 3
# Decreasing triangle pattern in Python

def decreasing_triangle_pattern():
    rows = 5
    for i in range(rows, 0, -1):
        print('* ' * i)

# Call the function to print the pattern
decreasing_triangle_pattern()

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
#Exercise 4
# Function to reverse a string in Python

def reverse_string():
    user_input = input("Enter a string to reverse: ")
    reversed_string = user_input[::-1]
    print("Reversed string:", reversed_string)

# Call the function to reverse a string
reverse_string()


Reversed string: 'nawi olleh'


In [11]:
#Exercise 5
def find_min_max(numbers):
    # Return both min and max values
    return min(numbers), max(numbers)

# Example usage:
numbers = [11, 30, 1, 5, 20]
min_val, max_val = find_min_max(numbers)

# Print the results with additional string literals
print(f"Min value is: {min_val}")
print(f"Max value is: {max_val}")

Min value is: 1
Max value is: 30


In [14]:
#Exercise 6 
import random

# Step 1: Choose a secret number between 1 and 10
secret_number = random.randint(1, 10)

# Step 2: Start the game
print("Welcome to the Guessing Game!")
print("I have chosen a secret number between 1 and 10. Can you guess it?")

# Initialize the guess to None to enter the loop
guess = None

# Step 3: Use a while loop to keep asking for guesses
while guess != secret_number:
    # Step 4: Get user input and convert it to an integer
    guess = int(input("Enter your guess: "))
    
    # Step 5: Compare the guess with the secret number
    if guess < secret_number:
        print("Too low! Try again.")
    elif guess > secret_number:
        print("Too high! Try again.")
    else:
        print("Congratulations! You guessed the correct number.")

Welcome to the Guessing Game!
I have chosen a secret number between 1 and 10. Can you guess it?
Too low! Try again.
Too low! Try again.
Congratulations! You guessed the correct number.


In [16]:
#Exercise 7
# Set the correct password
correct_password = "BigData2025"

# Start an infinite loop
while True:
    # Prompt the user to enter a password
    entered_password = input("Please enter your password: ")
    
    # Check if the entered password is correct
    if entered_password == correct_password:
        print("Access Granted!")
        break  # Exit the loop if the password is correct
    else:
        print("Incorrect password. Try again.")

Access Granted!


In [18]:
#Exercise 8
import math

def solve_series(x, N):
    result = 0
    for i in range(1, N + 1):
        result += (x * (5 ** (i + 1))) / (i + math.factorial(i))
    return result

# Get user input for x and N
x = float(input("Enter the value of x: "))
N = int(input("Enter the value of N: "))

# Call the function to solve the series
result = solve_series(x, N)

# Print the result
print(f"The result of the series is: {result}")

The result of the series is: 6417.710927747493


In [ ]:
#Exercise 10 
import numpy as np

# Temperature data in Celsius
temperatures_celsius = np.array([22, 24, 19, 21, 23, 25, 26, 27, 24, 23, 20, 22, 21, 19, 18, 22, 23, 24, 26,
                                 28, 30, 27, 25, 26, 24, 22, 21, 20, 19, 23])

# 1) Create a NumPy array
temp_array = temperatures_celsius

# 2) Find the minimum, maximum, and average temperature
min_temp = np.min(temp_array)
max_temp = np.max(temp_array)
average_temp = np.mean(temp_array)

print(f"Minimum temperature: {min_temp}°C")
print(f"Maximum temperature: {max_temp}°C")
print(f"Average temperature: {average_temp:.2f}°C")

# 3) Convert the temperatures from Celsius to Fahrenheit and store it in a new array
temperatures_fahrenheit = (temp_array * 9/5) + 32

print("Temperatures in Fahrenheit:", temperatures_fahrenheit)

# 4) Find all days where the temperature was above 25°C
above_25_celsius = temp_array[temp_array > 25]

print("Days with temperatures above 25°C:", above_25_celsius)

# 5) Count how many days had temperatures below 20°C
below_20_count = np.sum(temp_array < 20)

print(f"Number of days with temperatures below 20°C: {below_20_count}")

# 6) Sort the temperature data in ascending order
sorted_temps = np.sort(temp_array)

print("Sorted temperatures:", sorted_temps)

# 7) Reshape the 1D array into a 5x6 2D array representing weeks (5 weeks of 6 days each)
reshaped_array = temp_array.reshape(5, 6)

print("5x6 2D array representing weeks (5 weeks of 6 days each):")
print(reshaped_array)


Minimum temperature: 18°C
Maximum temperature: 30°C
Average temperature: 23.13°C
Temperatures in Fahrenheit: [71.6 75.2 66.2 69.8 73.4 77.  78.8 80.6 75.2 73.4 68.  71.6 69.8 66.2
 64.4 71.6 73.4 75.2 78.8 82.4 86.  80.6 77.  78.8 75.2 71.6 69.8 68.
 66.2 73.4]
Days with temperatures above 25°C: [26 27 26 28 30 27 26]
Number of days with temperatures below 20°C: 4
Sorted temperatures: [18 19 19 19 20 20 21 21 21 22 22 22 22 23 23 23 23 24 24 24 24 25 25 26
 26 26 27 27 28 30]
5x6 2D array representing weeks (5 weeks of 6 days each):
[[22 24 19 21 23 25]
 [26 27 24 23 20 22]
 [21 19 18 22 23 24]
 [26 28 30 27 25 26]
 [24 22 21 20 19 23]]
